server:
  port: 8080
  servlet:
    context-path: /hotelManagement


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 210MB
  application:
    name: main
  web:
    resources:
      static-locations: file:./uploads/
  datasource:
    url: "jdbc:mysql://localhost:3306/hotel-management-db"
    username: root
    password: 11111111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
file:
  upload-dir: uploads

